### ISSUE TITLE
Two Issues with the Tutorial

### ISSUE THREAD

**Issue by Kaltzifar** [ros2-for-arm/ros2#6]
Hy together,

I tried your tutorial for ros2 on arm with bouncy release.

1.) The first thing i noticed is that the build will fail because colcon builds by default with tests. Which wasn't the case with ament. Does a flag exist which disables building with tests when using colcon?

2.) The other thing is the last part of the tutorial. You mention the following 
> Once the compilation is done you will have to move the generated libraries (`install/lib`) in your target filesystem.

When I successfully compile the source code I have all ros2 packages under `install `and not `lib`. All `lib` folders are distributed between the packages, e.g. `install/a/lib`, `install/b/lib` and so on. Is this intended? It's gonna be pretty exhausting copying all `lib` folders. Is it because colcon builds per default as isolated now?

3.) The last is thing is not an issue but a question. Is it meant that you don't source the local_setup.bash? It is not mentioned in the tutorial. I'm a little bit confused if it is necessary.

Best regards

**Comment by pokitoz** [comment]
Hello,
The current tutorial has not been updated to work for the latest release of ROS2 (Bouncy). So many instructions do not apply anymore. 

1. To disable the tests you can use ` --cmake-args -DBUILD_TESTING:BOOL=OFF`
2. Yes, colcon is isolating all the libraries. You can use  `cp` `` `find . -name "*.so*"` `` `destination_folder`

3. If you update the `LD_LIBRARY_PATH` to find all the libraries needed then the sourcing of the script is not necessary. 

If you want, you can have a look at this issue: https://github.com/ros2-for-arm/ros2/issues/5 and follow the script given to build using colcon.
