### ISSUE TITLE
Problems installing gcc/g++

### ISSUE THREAD

**Issue by ghost** [ros2-for-arm/ros2#8]
I am trying to follow your instructions in the wiki. At the moment I am stuck at the "Get an aarch64 toolchain and export it" step.

When I try to run `sudo apt install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu` I get this error message:   

>  Package gcc-aarch64-linux-gnu is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source
>
>     Package g++-aarch64-linux-gnu is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source
>
>     E: Package 'g++-aarch64-linux-gnu' has no installation candidate E: Package 'gcc-aarch64-linux-gnu' has no installation candidate

My `/etc/apt/sources.list` contains

> 
> deb http://ports.ubuntu.com/ubuntu-ports bionic main universe
> deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main universe
> deb http://ports.ubuntu.com/ubuntu-ports bionic-security main universe

I am running Ubuntu 18.04 on a raspberry pi 3.
I would be glad if you could help me with this (:

**Comment by pokitoz** [comment]
Hello ! 

You would like to cross-compile ROS2 for an Arm platform on an Arm Platform?
You are saying that you use Ubuntu on a Raspberry Pi3. I think you should try a native installation as described in https://github.com/ros2/ros2/wiki/Linux-Development-Setup

The toolchain in your Raspberry Pi3 should already be an Arm based one and I am not sure why you want to cross-compile for Arm.

**Comment by ghost** [comment]
Oh boy, my fault. I didn't see that the instructions were for cross compiling
